import type { Metadata } from "next";
import { FadeIn } from "@/components/motion";
import { Button, PageHeader, Section, SpecRow } from "@/components/primitives";
import { githubUser, links, person } from "@/content/site";
import { getGithubSnapshot, relativeTime } from "@/lib/github";

export const metadata: Metadata = {
  title: "GitHub",
  description: `Live GitHub statistics, language breakdown and contribution activity for ${person.name}.`,
  alternates: { canonical: "/github" },
};

/** Third-party stat cards. Query strings are pinned to the site palette so the
 *  cards do not arrive in someone else's colours. */
const cards = [
  {
    title: "Statistics",
    src: `https://github-readme-stats.vercel.app/api?username=${githubUser}&show_icons=true&hide_border=true&bg_color=00000000&title_color=0f7a72&icon_color=0f7a72&text_color=4b5250&hide_title=true`,
    alt: `GitHub statistics for ${githubUser}`,
    width: 480,
    height: 195,
  },
  {
    title: "Top languages",
    src: `https://github-readme-stats.vercel.app/api/top-langs/?username=${githubUser}&layout=compact&hide_border=true&bg_color=00000000&title_color=0f7a72&text_color=4b5250&hide_title=true`,
    alt: `Most used languages for ${githubUser}`,
    width: 480,
    height: 195,
  },
  {
    title: "Streak",
    src: `https://streak-stats.demolab.com?user=${githubUser}&hide_border=true&background=00000000&ring=0F7A72&fire=0F7A72&currStreakLabel=4B5250&sideLabels=4B5250&dates=9AA09D&sideNums=4B5250&currStreakNum=0F7A72`,
    alt: `Contribution streak for ${githubUser}`,
    width: 480,
    height: 195,
  },
];

export default async function GithubPage() {
  const gh = await getGithubSnapshot();
  const languages = [...new Set(gh.repos.map((r) => r.language).filter(Boolean))];
  const mostRecent = gh.repos[0];

  return (
    <div className="shell">
      <PageHeader
        eyebrow="GitHub"
        title="The activity behind the projects."
        lede={
          "Repository activity, language breakdown and contribution history, pulled " +
          "live from the GitHub API."
        }
      />

      <Section title="Profile" aside={gh.live ? "Live" : "Cached snapshot"}>
        <dl className="border-b border-rule">
          <SpecRow label="Handle">
            <a
              href={links.github}
              target="_blank"
              rel="noreferrer noopener"
              className="link-underline mono"
            >
              {githubUser} ↗
            </a>
          </SpecRow>
          <SpecRow label="Public repos">{gh.publicRepos}</SpecRow>
          <SpecRow label="Followers">{gh.followers}</SpecRow>
          <SpecRow label="Languages">{languages.join(" · ") || "—"}</SpecRow>
          <SpecRow label="Last push">
            {mostRecent
              ? `${mostRecent.name} · ${relativeTime(mostRecent.updated)}`
              : "—"}
          </SpecRow>
        </dl>
      </Section>

      <Section title="Contribution graph">
        <div className="overflow-x-auto rounded-sm border border-rule p-4">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={`https://ghchart.rshah.org/0f7a72/${githubUser}`}
            alt={`Contribution graph for ${githubUser}`}
            width={880}
            height={128}
            loading="lazy"
            decoding="async"
            className="min-w-[640px]"
          />
        </div>
      </Section>

      <Section title="Statistics" aside="Rendered by third-party services">
        <ul className="grid gap-px bg-rule lg:grid-cols-3">
          {cards.map((card, i) => (
            <li key={card.title} className="surface p-6">
              <FadeIn delay={i * 0.07}>
                <p className="label mb-4">{card.title}</p>
                {/* These are rendered SVGs with baked-in type. Scaled to a
                    320px column the labels drop below legibility, so the card
                    keeps its natural width inside a scroll region instead of
                    being squashed. */}
                <div className="-mx-2 overflow-x-auto px-2">
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={card.src}
                    alt={card.alt}
                    width={card.width}
                    height={card.height}
                    loading="lazy"
                    decoding="async"
                    className="h-auto w-full min-w-[380px] max-w-[480px]"
                  />
                </div>
              </FadeIn>
            </li>
          ))}
        </ul>
        <p className="label mt-6">
          These cards are generated by external services. If one is down its panel is
          empty; nothing else on the page is affected.
        </p>
      </Section>

      <Section title="Repositories">
        {/* This page is statistics. The repositories themselves live on
            /open-source — one canonical list, not two that can disagree. */}
        <div className="flex flex-wrap items-end justify-between gap-6">
          <p className="prose-measure text-lead text-fg-muted">
            The repositories, with descriptions and what each one is for, are on the open
            source page.
          </p>
          <div className="flex flex-wrap gap-3">
            <Button href="/open-source">Browse repositories</Button>
            <Button href={links.github} variant="outline" external>
              Full profile
            </Button>
          </div>
        </div>
      </Section>
    </div>
  );
}
